# Change these first
owner: leonic15 # Your GitHub organization or username, where this repository lives
repo: cfa-azure-monitoreo # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Web Partners
    url: https://efectivosi-azure.epidataconsulting.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

assignees:
  - leonic15
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /cfa-azure-monitoreo
  logoUrl: https://media.licdn.cn/dms/image/C4E0BAQHY06rwmffzZQ/company-logo_200_200/0/1563368861383?e=2159024400&v=beta&t=tSZPtIC4FiJOtSP_ItGEoJtfe4S6kCSPJKvqBbNrHWg
  name: CFA Efectivo Si - Monitoreo
  introTitle: "Sitio web de monitoreo de CFA Efectivo SI en Azure"
  introMessage: "Status"
  navbar:
    - title: Status
      href: https://leonic15.github.io/cfa-azure-monitoreo/
   
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
